name: benchmarks
permissions:
  contents: read

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod

      - name: Run benchmarks
        run: |
          set -o pipefail
          make benchmarks | tee benchmark.txt

      - name: Download previous benchmark data
        id: benchmark-cache
        uses: actions/cache/restore@v6
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-benchmark-

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: go
          output-file-path: benchmark.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          summary-always: true

      - name: Save benchmark data
        uses: actions/cache/save@v6
        if: always()
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark-${{ github.run_id }}
