name: tests
permissions:
  contents: read

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version-file: go.mod

    - name: Test
      run: make coverage

    - name: Run race benchmarks
      run: make benchmarks-race

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Update Coveralls
      if: ${{ hashFiles('coverage.out') != '' }}
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
